version: 2

sources:
  - name: source
    database: "{{ env_var('DBT_DATABRICKS_CATALOG') }}"
    schema: "{{ env_var('DBT_DATABRICKS_SCHEMA') }}"
    tables:
      - name: dim_customer
      - name: dim_date
      - name: dim_product
      - name: dim_store
      - name: fact_returns
      - name: fact_sales
