[project]
name = "dbt-dbx"
version = "0.1.0"
description = "A streamlined dbt workflow optimized for scalable data transformations on Databricks."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt>=1.0.0.40.16",
    "dbt-core>=1.11.8",
    "dbt-databricks>=1.11.7"
]

[dependency-groups]
dev = [
    "shandy-sqlfmt[jinjafmt]>=0.30.0",
]
